[tools]
bun = "1.3.2"

[env]
_.path = "node_modules/.bin"

[settings]
experimental = true
pin = true

[tasks.dev]
run = "vite dev"

[tasks.build]
run = "vite build"

[tasks.preview]
run = "vite preview"

[tasks.prepare]
run = "svelte-kit sync || echo ''"

[tasks.check]
run = "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json"

[tasks."check:watch"]
run = "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch"

[tasks.format]
alias = "fmt"
run = "prettier --write ."

[tasks."format:check"]
run = "prettier --check ."

[tasks.deploy]
run = "alchemy deploy"

[tasks.destroy]
run = "alchemy destroy"
